### ISSUE TITLE
hi I find u on teamliquid

### ISSUE THREAD

**Issue by jason19659** [spinesheath/TenView#35]
I get something like that from tenhou
````
{"tag":"e125"}
{"tag":"N","m":"47627","who":"2"} //对家碰白

{"tag":"N","m":"14848","who":"2"} //暗杠6s
{"hai":"103","tag":"DORA"} //dora指示牌

{"tag":"D39"}
{"tag":"N","m":"14889","who":"3"}  //碰1p

{"tag":"D7"}
{"tag":"N","m":"2602","who":"2"} //对家碰2m

{"t":"4","tag":"g100"}
send : {"tag":"N"}
{"tag":"N","m":"25601","who":"2"} //明杠8s
````

do you know why m equals those numbers...
thanks a lot

**Comment by spinesheath** [comment]
This is weird on so many levels. Why did you post this here, it's obviously not an issue in this project. Why is the title of the issue a greeting? Why didn't you just PM me on TL?

Anyways... "m" is what I call the "meldCode". That together with the "ownerId" ("who") lets you decode the tiles in a meld. I have no idea WHY it is that way, but there IS code in this repository for decoding it. Start here:
https://github.com/spinesheath/HanaMahjong/blob/master/Spines.Mahjong/Spines.Tenhou.Client/MeldCode.cs
